coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 90%

ignore:
  - "tests/*"
  - "external/*"

comment:
  layout: "files"
  require_changes: true
