name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
            submodules: 'recursive'

      - name: Configure CMake
        run: cmake -S . -B build --preset coverage

      - name: Run coverage
        run: cmake --build build --target ccov-all


      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build-coverage/ccov/ccov-all.info
          disable_search: true
          fail_ci_if_error: true
          gcov_ignore: "*/tests/*,*/external/*"
          verbose: true
