name: clang-coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
            submodules: 'recursive'

      - name: Install Clang + llvm-cov
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm

      - name: Configure CMake (Clang coverage)
        env:
          CC: clang
          CXX: clang++
        run: cmake -S . -B build -DCODE_COVERAGE=ON 

      - name: Build DandanLibTest with coverage
        run: cmake --build build --parallel --target ccov-DandanLibTest

      - name: Build DandanLibSerializationTest with coverage
        run: cmake --build build --parallel --target ccov-DandanLibSerializationTest

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: build
          fail_ci_if_error: true
          verbose: true
