name: cppcheck

on:
  push:
  pull_request:

jobs:
  cppcheck:
    name: Run Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with: 
            submodules: 'recursive'

      - name: Install dependencies
        run: sudo apt-get install -y cppcheck cmake clang-tidy
      
      - name: Configure with CMake
        run: cmake -B build --preset=DandanWithSerialize -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
      - name: Run clang-tidy
        run: |
          run-clang-tidy \
            -p build \
            '.*/(include/dandan|src/dandan|src/main\.cpp).*'

      - name: run cppcheck
        run: |
          cppcheck \
            --project=build/compile_commands.json \
            --std=c++17 \
            --enable=all \
            --check-level=exhaustive \
            --inconclusive \
            --error-exitcode=1 \
            --suppress=*:external/* \
            --suppress=missingIncludeSystem \
            --suppress=missingInclude \

